package model

type Inbound struct {
	ID          int64          `json:"id"`
	Remark      string         `json:"remark"`
	Port        int            `json:"port"`
	Protocol    string         `json:"protocol"`
	Password    string         `json:"password,omitempty"`
	UUID        string         `json:"uuid,omitempty"`
	Email       string         `json:"email,omitempty"`
	Method      string         `json:"method,omitempty"`
	Flow        string         `json:"flow,omitempty"`
	Network     string         `json:"network,omitempty"`
	Security    string         `json:"security,omitempty"`
	SNI         string         `json:"sni,omitempty"`
	Host        string         `json:"host,omitempty"`
	Path        string         `json:"path,omitempty"`
	RealityDest string         `json:"realityDest,omitempty"`
	ShortID     string         `json:"shortId,omitempty"`
	PublicKey   string         `json:"publicKey,omitempty"`
	PrivateKey  string         `json:"privateKey,omitempty"`
	Enable      bool           `json:"enable"`
	Settings    map[string]any `json:"settings,omitempty"`
	Stream      map[string]any `json:"streamSettings,omitempty"`
	Extra            map[string]any `json:"extra,omitempty"`
	SniffingEnabled  bool           `json:"sniffingEnabled"`
	SniffingOverride string         `json:"sniffingDestOverride,omitempty"`
	CreateUnix       int64          `json:"createUnix"`
	UpdateUnix       int64          `json:"updateUnix"`
}

type AddInboundRequest struct {
	Remark         string `json:"remark"`
	Port           int    `json:"port"`
	Protocol       string `json:"protocol"`
	Password       string `json:"password"`
	UUID           string `json:"uuid"`
	Email          string `json:"email"`
	Method         string `json:"method"`
	Flow           string `json:"flow"`
	Network        string `json:"network"`
	Security       string `json:"security"`
	SNI            string `json:"sni"`
	Host           string `json:"host"`
	Path           string `json:"path"`
	RealityDest    string `json:"realityDest"`
	ShortID        string `json:"shortId"`
	PublicKey      string `json:"publicKey"`
	PrivateKey     string `json:"privateKey"`
	HY2HopPorts    string `json:"hy2HopPorts"`
	HY2HopInterval string `json:"hy2HopInterval"`
	TargetAddress      string `json:"targetAddress"`
	TargetPort         int    `json:"targetPort"`
	Auth               string `json:"auth"`
	AccountUser        string `json:"accountUser"`
	AccountPass        string `json:"accountPass"`
	WireguardSecretKey string `json:"wireguardSecretKey"`
	WireguardAddress   string `json:"wireguardAddress"`
	WireguardMTU       int    `json:"wireguardMtu"`
	WireguardReserved  string `json:"wireguardReserved"`
	TunName            string `json:"tunName"`
	TunMTU             int    `json:"tunMtu"`
	TunStack           string `json:"tunStack"`
	TunAutoRoute       bool   `json:"tunAutoRoute"`
	TunStrictRoute     bool   `json:"tunStrictRoute"`
	SniffingEnabled    *bool  `json:"sniffingEnabled"`
	SniffingOverride   string `json:"sniffingDestOverride"`
	Enable             *bool  `json:"enable"`
	ExpiryTime         int64          `json:"expiryTime"`
	HY2Obfs            string         `json:"hy2Obfs"`
	HY2ObfsPassword    string         `json:"hy2ObfsPassword"`
	HY2Congestion      string         `json:"hy2Congestion"`
	HY2UpMbps          int            `json:"hy2UpMbps"`
	HY2DownMbps        int            `json:"hy2DownMbps"`
	HY2IdleTimeout     int            `json:"hy2IdleTimeout"`
	HY2KeepAlive       int            `json:"hy2KeepAlivePeriod"`
	HY2InitStreamRW    int            `json:"hy2InitStreamReceiveWindow"`
	HY2MaxStreamRW     int            `json:"hy2MaxStreamReceiveWindow"`
	HY2InitConnRW      int            `json:"hy2InitConnectionReceiveWindow"`
	HY2MaxConnRW       int            `json:"hy2MaxConnectionReceiveWindow"`
	HY2DisableMTUDisc  *bool          `json:"hy2DisableMtuDiscovery"`
	SettingsOverride   map[string]any `json:"settingsOverride"`
	StreamOverride     map[string]any `json:"streamOverride"`
}
